sequence:
  name: sequence
  description: "Run a sequence of services"
  fields:
    browser_id:
      name: Target Browser
      description: ""
      selector:
        device:
          multiple: true
          filter:
            integration: "browser_mod"
    user_id:
      name: Target User
      description: ""
      selector:
        entity:
          multiple: true
          filter:
            domain: "person"
    sequence:
      name: Actions
      description: List of services to run
      selector:
        object:

delay:
  name: delay
  description: "Wait for a time"
  fields:
    browser_id:
      name: Target Browser
      description: ""
      selector:
        device:
          multiple: true
          filter:
            integration: "browser_mod"
    user_id:
      name: Target User
      description: ""
      selector:
        entity:
          multiple: true
          filter:
            domain: "person"
    time:
      name: Time
      description: Time to wait (ms)
      selector:
        number:
          mode: box

popup:
  name: popup
  description: "Display a popup"
  fields:
    browser_id:
      name: Target Browser
      description: ""
      selector:
        device:
          multiple: true
          filter:
            integration: "browser_mod"
    user_id:
      name: Target User
      description: ""
      selector:
        entity:
          multiple: true
          filter:
            domain: "person"
    popup_card_id:
      name: Popup-card ID
      description: ID of the popup-card to use as a template for the popup
      selector:
        text:
    title:
      name: Title
      description: "Popup title"
      selector:
        text:
    content:
      name: Content
      required: true
      description: "Popup content (Test or lovelace card configuration)"
      selector:
        object:
    size:
      name: Size
      description: ""
      selector:
        select:
          mode: dropdown
          options:
            - normal
            - classic
            - wide
            - fullscreen
    right_button:
      name: Right button
      description: Text of the right button
      selector:
        text:
    right_button_variant:
      name: Right button variant
      description: Variant of the right button
      selector:
        select:
          mode: dropdown
          options:
            - brand
            - neutral
            - danger
            - warning
            - success
    right_button_appearance:
      name: Right button appearance
      description: Appearance of the right button
      selector:
        select:
          mode: dropdown
          options:
            - accent
            - filled
            - outlined
            - plain
    right_button_action:
      name: Right button action
      description: Action to perform when the right button is pressed
      selector:
        object:
    left_button:
      name: Left button
      description: Text of the left button
      selector:
        text:
    left_button_variant:
      name: Left button variant
      description: Variant of the left button
      selector:
        select:
          mode: dropdown
          options:
            - brand
            - neutral
            - danger
            - warning
            - success
    left_button_appearance:
      name: Left button appearance
      description: Appearance of the left button
      selector:
        select:
          mode: dropdown
          options:
            - accent
            - filled
            - outlined
            - plain
    left_button_action:
      name: Left button action
      description: Action to perform when left button is pressed
      selector:
        object:
    dismissable:
      name: User dismissable
      description: Whether the popup can be closed by the user without action
      default: true
      selector:
        boolean:
    dismiss_action:
      name: Dismiss action
      description: Action to perform when popup is dismissed
      selector:
        object:
    autoclose:
      name: Auto close
      description: Close the popup automatically on mouse, pointer or keyboard activity
      default: false
      selector:
        boolean:
    timeout:
      name: Auto close timeout
      description: Time before closing (ms)
      selector:
        number:
          mode: box
    timeout_action:
      name: Timeout action
      description: Action to perform when popup is closed by timeout
      selector:
        object:
    timeout_hide_progress:
      name: Hide timeout progress
      description: Hide timeout progress bar
      selector:
        boolean:
    tag:
      name: Tag
      description: Tag for managing multiple popups
      selector:
        text:
    style:
      name: Styles
      description: CSS code to apply to the popup window
      selector:
        text:
          multiline: true

more_info:
  name: more_info
  description: "Show more-info dialog"
  fields:
    browser_id:
      name: Target Browser
      description: ""
      selector:
        device:
          multiple: true
          filter:
            integration: "browser_mod"
    user_id:
      name: Target User
      description: ""
      selector:
        entity:
          multiple: true
          filter:
            domain: "person"
    entity:
      name: Entity ID
      description: ""
      selector:
        text:
    large:
      name: Large size
      description: ""
      default: false
      selector:
        boolean:
    ignore_popup_card:
      name: Ignore any active popup-card overrides
      description: ""
      default: false
      selector:
        boolean:

close_popup:
  name: close_popup
  description: "Close a popup"
  fields:
    browser_id:
      name: Target Browser
      description: ""
      selector:
        device:
          multiple: true
          filter:
            integration: "browser_mod"
    user_id:
      name: Target User
      description: ""
      selector:
        entity:
          multiple: true
          filter:
            domain: "person"
    all:
      name: All popups
      description: Close all Browser Mod popups on the browser
      default: false
      selector:
        boolean:
    tag:
      name: Tag
      description: Tag for popup to close when using multiple popups
      selector:
        text:

notification:
  name: notification
  description: "Display a short notification"
  fields:
    browser_id:
      name: Target Browser
      description: ""
      selector:
        device:
          multiple: true
          filter:
            integration: "browser_mod"
    user_id:
      name: Target User
      description: ""
      selector:
        entity:
          multiple: true
          filter:
            domain: "person"
    message:
      name: Message
      description: "Message to display"
      required: true
      selector:
        text:
    duration:
      name: Auto close timeout
      description: Time before closing (ms)
      selector:
        number:
          mode: box
    action_text:
      name: Action button text
      description: Text of optional action button
      selector:
        text:
    action:
      name: Button action
      description: Action to perform when the action button is pressed
      selector:
        object:

navigate:
  name: navigate
  description: "Navigate browser to a different page"
  fields:
    browser_id:
      name: Target Browser
      description: ""
      selector:
        device:
          multiple: true
          filter:
            integration: "browser_mod"
    user_id:
      name: Target User
      description: ""
      selector:
        entity:
          multiple: true
          filter:
            domain: "person"
    path:
      name: Path
      description: "Target path"
      selector:
        text:

refresh:
  name: refresh
  description: "Refresh page"
  fields:
    browser_id:
      name: Target Browser
      description: ""
      selector:
        device:
          multiple: true
          filter:
            integration: "browser_mod"
    user_id:
      name: Target User
      description: ""
      selector:
        entity:
          multiple: true
          filter:
            domain: "person"

change_browser_id:
  name: change_browser_id
  description: "Change browser ID" 
  fields:
    current_browser_id:
      name: Current Browser ID
      description: "Current Browser ID of the browser to change"
      selector:
        device:
          multiple: false
          filter:
            integration: "browser_mod"
    new_browser_id:
      name: New ID
      description: "New Browser ID for the browser"
      selector:
        text:
    register:
      name: Register
      description: "Register the browser"
      selector:
        boolean:
    refresh:
      name: Refresh
      description: "Refresh the browser after changing the ID"
      default: true
      selector:
        boolean:

set_theme:
  name: set_theme
  description: "Change the current theme"
  fields:
    browser_id:
      name: Target Browser
      description: ""
      selector:
        device:
          multiple: true
          filter:
            integration: "browser_mod"
    user_id:
      name: Target User
      description: ""
      selector:
        entity:
          multiple: true
          filter:
            domain: "person"
    theme:
      name: Theme
      description: "Name of theme or 'auto'"
      selector:
        text:
    dark:
      name: Mode
      description: "Dark/light mode"
      selector:
        select:
          options:
            - auto
            - light
            - dark
    primaryColor:
      name: Primary Color
      description: "Primary theme color"
      selector:
        color_rgb:
    accentColor:
      name: Accent Color
      description: "Accent theme color"
      selector:
        color_rgb:

console:
  name: console
  description: "Print text to browser console"
  fields:
    browser_id:
      name: Target Browser
      description: ""
      selector:
        device:
          multiple: true
          filter:
            integration: "browser_mod"
    user_id:
      name: Target User
      description: ""
      selector:
        entity:
          multiple: true
          filter:
            domain: "person"
    message:
      name: Message
      description: "Text to print"
      selector:
        text:

javascript:
  name: javascript
  description: "Run arbitrary JavaScript code"
  fields:
    browser_id:
      name: Target Browser
      description: ""
      selector:
        device:
          multiple: true
          filter:
            integration: "browser_mod"
    user_id:
      name: Target User
      description: ""
      selector:
        entity:
          multiple: true
          filter:
            domain: "person"
    code:
      name: Code
      description: "JavaScript code to run"
      selector:
        object:

deregister_browser:
  name: deregister_browser
  description: "Deregister a browser. Include at leaset one paremeter. Calling wiith either exclude parameter will deregister all browsers except those excluded."
  fields:
    browser_id:
      name: Target Browsers
      description: ""
      selector:
        device:
          multiple: true
          filter:
            integration: "browser_mod"
    browser_id_exclude:
      name: Browsers to exclude
      description: "Exclude browser from deregister"
      selector:
        device:
          multiple: true
          filter:
            integration: "browser_mod"
    area_id_exclude:
      name: Areas to exclude
      description: "Exclude browsers in area from deregister"
      selector:
        area:
          multiple: true
          entity:
            integration: "browser_mod"